name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image to Docker Hub
    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/personal-portfolio:latest --push .

    # Step 4: Deploy to Render
    - name: Deploy to Render
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"serviceId\": \"${{ secrets.RENDER_SERVICE_ID }}\", \"clearCache\": false}" \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
